### ISSUE TITLE
nody greeter setup questions and issues

### ISSUE THREAD

**Issue by Hellzbellz123** [JezerM/nody-greeter#1]
Im trying to setup nody-greeter and ive managed to get everything more or less setup but whenever i try to launch debug mode i get a javascript error and then a black screen when the greeter finally loads. the greeter renders correctly until i press okay on the notification.

<pre><font color="#00AA00"><b>[hellzbellz@bertiebottpc</b></font><font color="#AAAAAA"><b> ~</b></font><font color="#00AA00"><b>]$</b></font> nody-greeter --debug
<span style="background-color:#AAAAAA"><font color="#AA0000"><b>A JavaScript error occurred in the main process</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>Uncaught Exception:</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>Error: Unable to determine socket to daemon</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at new Greeter (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:44:24)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Object.&lt;anonymous&gt; (/opt/nody-greeter/resources/app.asar/js/bridge/bridge.js:601:1)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Module._compile (internal/modules/cjs/loader.js:1078:30)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Module.load (internal/modules/cjs/loader.js:935:32)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Module._load (internal/modules/cjs/loader.js:776:14)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Module.require (internal/modules/cjs/loader.js:959:19)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at require (internal/modules/cjs/helpers.js:88:18)</b></font></span>
<span style="background-color:#AAAAAA"><font color="#000000"><b>    at Object.&lt;anonymous&gt; (/opt/nody-greeter/resources/app.asar/js/index.js:71:1)</b></font></span>
2021-09-11 01:40:02 [ DEBUG ] undefined undefined: Restarting acpi_listen
2021-09-11 01:40:03 [ DEBUG ] browser.js 134: Initializing Browser Window
2021-09-11 01:40:03 [ DEBUG ] browser.js 155: Browser Window created
2021-09-11 01:40:03 [ DEBUG ] browser.js 126: Theme loaded
2021-09-11 01:40:03 [ DEBUG ] globals.js 63: Logger is ready
2021-09-11 01:40:03 [ DEBUG ] globals.js 36: Window is ready
2021-09-11 01:40:03 [ DEBUG ] undefined undefined: Restarting acpi_listen
2021-09-11 01:40:03 [ DEBUG ] undefined undefined: Restarting acpi_listen
2021-09-11 01:40:03 [ DEBUG ] screensaver.js 49: Screensaver set
2021-09-11 01:40:03 [ DEBUG ] undefined undefined: Restarting acpi_listen
2021-09-11 01:40:03 [ DEBUG ] undefined undefined: Restarting acpi_listen
2021-09-11 01:40:05 [ DEBUG ] browser.js 178: Nody Greeter started
2021-09-11 01:40:38 [ DEBUG ] screensaver.js 61: Screensaver reset
</pre>
i tried with both prebuilt binary and building from source

just noticed the java error is different from terminal output,
![Screenshot from 2021-09-11 01-51-26](https://user-images.githubusercontent.com/31550512/132942308-32cd2b88-9119-44a5-b373-86dc5e3746c6.png)
![Screenshot from 2021-09-11 01-50-25](https://user-images.githubusercontent.com/31550512/132942311-1b934a37-97b2-4cc1-b562-5d8a1ffe1b98.png)

**Comment by JezerM** [comment]
The error alerts are only about JavaScript problems. Maybe I should change that.

If you're trying this on a desktop environment, maybe you didn't add the `X-LightDM-Allow-Greeter=true` line inside your xsession. Check [here](https://github.com/JezerM/web-greeter#debugging).
