### ISSUE TITLE
Error on Lubuntu 21.10 upon signing in with "Simple" theme

### ISSUE THREAD

**Issue by ro1y** [JezerM/nody-greeter#14]
## Environment
- OS: Lubuntu 21.10
- nody-greeter version: output of `nody-greeter --version`

## Bug description
When signing on with the "Simple" theme or [WelcomeXP](https://github.com/mshernandez5/WelcomeXP/) theme the log on fails.

## Steps to reproduce
Use "Simple" theme or WelcomeXP theme (the theme where I found this bug)

## Expected behavior
Successful log on

## Screenshots
A screenshot of the error on WelcomeXP theme, the same error pops up when logging on with the "Simple" theme.
![149672277-4c3b0be3-221e-4c7f-a02b-275c05455418](https://user-images.githubusercontent.com/76408418/149674940-59d787ef-0d67-409f-8e03-16ed2b232e2d.jpg)

**Comment by JezerM** [comment]
How did you install nody-greeter? If possible, provide the log inside `/var/log/lightdm/seat0-greeter.log`. Also, you could try to run `nody-greeter --debug --theme simple` inside your session and provide the log~

**Comment by ro1y** [comment]
The problem was solved over at https://github.com/mshernandez5/WelcomeXP/issues/10 . It was that the default user session wasn't set.

**Comment by JezerM** [comment]
Oh, `session-default` not set. I'll try to put a better error message when this occurs.
