### ISSUE TITLE
Not starting anymore, GPU process isn't usable. Goodbye?

### ISSUE THREAD

**Issue by Crylia** [JezerM/nody-greeter#22]
## Environment
- OS: Pop_OS! 22.04
- nody-greeter version: 1.4.1

## Bug description
Trying to start gives me the following output [Logs]()

## Steps to reproduce
*Reinstalled as described

## Expected behavior
It should start

##Logs
2022-04-26 01:47:44 [ DEBUG ] browser.js 121: Initializing Browser Window
2022-04-26 01:47:44 [ DEBUG ] browser.js 173: Browser Window created
2022-04-26 01:47:44 [ DEBUG ] screensaver.js 40: Screensaver set
2022-04-26 01:47:44 [ DEBUG ] browser.js 118: Theme loaded
2022-04-26 01:47:44 [ DEBUG ] globals.js 16: Javascript logger is ready
2022-04-26 01:47:44 [ DEBUG ] globals.js 13: Window is ready
2022-04-26 01:47:44 [ ERROR ] bridge.js 48: Error: Unable to determine socket to daemon
2022-04-26 01:47:44 [ DEBUG ] bridge.js 65: LightDM API connected
[37985:0426/014745.377460:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    37985 trace trap (core dumped)  nody-greeter --debug

## /etc/lightdm/lightdm.conf

[Seat:*]
greeter-session=nody-greeter (using the default greeter works)
greeter-setup-script=/usr/bin/numlockx on (tried removing it, changed nothing)

## /etc/lightdm/web-greeter.yml

Default config.

*I did a complete reinstall since it stopped working after the update from 21.10 --> 22.04

**Comment by JezerM** [comment]
Hmm, this looks like the Fedora's error with these greeters. I'll try to look into this.

**Comment by Crylia** [comment]
Another problem I noticed is that my Laptop has a different error, after upgrading I was greeted with a blinking underscore and a flashing blackscreen, I think lightdm tried to start but couldnt for some reason. I now tried to purge everything lightdm related, reinstall it but no luck, it won't work anymore with the default config. This is really strange

**Comment by JezerM** [comment]
If LightDM is "flashing" or has a blinking underscore, that means that LightDM isn't correctly executing the greeter; this could be a X Server error, a Greeter (nody-greeter) error, or a LightDM issue.

Also, does this happen with web-greeter too? Maybe you could try lightdm-gtk-greeter and tell if it does work.

**Comment by Crylia** [comment]
Strangely enough it works when using `lightdm --test-mode --debug` with the lightdm-gtk-greeter, but not the nody-greeter or web-greeter. But now it gets even stranger, when using the lightdm-gtk-greeter, the one that worked with the command, doesnt work when booting up and results in the error from before.
I will give you the logs tomorrow since I have to go into recovery mode again and switch to gdm to be able to boot again.

**Comment by JezerM** [comment]
Hmm, perhaps this could be a LightDM error. Also, when you can, provide the `/var/log/lightdm/lightdm.log` log, it could show more info about the error.

**Comment by JezerM** [comment]
I managed to get it to work on a VM (UTM). Installed PopOS 22.04, then the latest release of nody-greeter with lightdm, set the `/etc/lightdm/lightdm.conf` with `greeter-session=nody-greeter` and the default `web-greeter.yml` configuration. Then, restart lightdm and it worked.


https://user-images.githubusercontent.com/59768785/165211447-ab5e6504-48e2-4f21-9aef-ec84fe2d0158.mp4


I don't know what the problem could be in your case.

**Comment by Crylia** [comment]
Alright, I think I found the issue, for whatever reason lightdm had no access to /var/lib/lightdm*. It had no permission to create the /var/lib/lightdm/.Xautorithy file.
I fixed it by doing chown lightdm:lightdm to every lightdm folder and file in /var/lib/.
