### ISSUE TITLE
How to run at system startup...?

### ISSUE THREAD

**Issue by NetMan134** [JezerM/nody-greeter#26]
Hi, I know - this might sound really dumb (because it probably is), how to actually execute this greeter at system startup?
I scoured the internet for solutions, tried modifying in `lightdm.conf` the "`greeter-session = web-greeter`", even used the archived `lightdm-webkit2-greeter` (it worked with setting "`greeter-session = lightdm-webkit2-greeter`" in the lightdm config, but I wasn't able to set your `lightdm-void-theme` https://github.com/JezerM/lightdm-void-theme which I'm interested in). The node-greeter command works though in my desktop environment and launches a greeter, but this isn't my goal.

OS: Void Linux x86_64
Kernel: 5.18.9_1

Thank you guys for any suggestions and help,
Oskar

**Comment by JezerM** [comment]
Hello~ First, if you wanna use one of these web based greeters, like nody-greeter, you need to install it and set `greeter-session=nody-greeter` at `/etc/lightdm/lightdm.conf`. If the `lightdm` service is not enabled, you should so: `sudo ln -s /etc/sv/lightdm /var/service/`.

These greeters come with three preinstalled themes: gruvbox (the default one), dracula and simple.

For **lightdm-void-theme**, you can follow the instructions in the [README](https://github.com/JezerM/lightdm-void-theme#build--install) to build the theme and copy it to `/usr/share/web-greeter/themes` where all themes should reside. You can use `nody-greeter --list` to list all installed themes; **lightdm-void-theme** should be listed.

Then, open your web-greeter/nody-greeter config file at `/etc/lightdm/web-greeter.yml` (it's the same config file for both greeters), and edit the `theme: gruvbox` value to `theme: lightdm-void-theme`:

```yml
greeter:
    ...
    theme: lightdm-void-theme
    ...
```

You could run `nody-greeter --debug` to preview your chosen theme, and if everything is okay, just let it stay~ Or restart the lightdm service to make sure everything is setup correctly.

**Comment by NetMan134** [comment]
Hi!
Thanks for your response - putting `nody-greeter` in the `lightdm.conf` did the trick. Everything else was already done and after a reboot it successfully loaded into nody-greeter. I think you should include that in the readme, but that's just my opinion - because didn't see people having this problem nor see this in the docs

Thanks again and have a great night (it's 12 AM in GMT+2 right now),
Oskar

**Comment by JezerM** [comment]
I'll add this step in the README just in case. Good night there~
