### ISSUE TITLE
failed to build asar package

### ISSUE THREAD

**Issue by LiveEmily** [JezerM/nody-greeter#29]
## Environment
- OS: Arch Linux
- nody-greeter version: 1.5.1

## Bug description
When trying to build, packaging the asar throws an error having to do with python.

## Steps to reproduce
Clone the repo recursively, install npm dependencies, run rebuild, run build.

## Expected behavior
Package should build successfully so you can continue with installing

## Screenshots
![image](https://user-images.githubusercontent.com/37963198/189522717-b5ad798b-a18b-4443-a4ef-bf6b69410d2a.png)

**Comment by JezerM** [comment]
Seems to be an upstream error about [node-gyp-bins](https://github.com/nodejs/node-gyp/issues/2713). I'll look for a solution soon~

**Comment by Cy1der** [comment]
Any fix yet?

**Comment by JezerM** [comment]
No, sorry, I haven't had time to see through this error.

**Comment by sachin746** [comment]
just trying to install this greeter same error 
![image](https://user-images.githubusercontent.com/56162613/193813287-0fc8ab66-880b-451d-976d-e0708f7bd122.png)

**Comment by JezerM** [comment]
Well, I fixed this issue by patching the asar package. This isn't ideal, and it's not the best way to do it as it should've been done in the node-gyp package, but it works. Tell me if it works~

**Comment by Cy1der** [comment]
Thanks, I will test it later today. Also, does this greeter work with themes for WebKit?

**Comment by Cy1der** [comment]
Now I'm unable to run `npm install`.
[2022-12-22T15_15_16_526Z-debug-0.log](https://github.com/JezerM/nody-greeter/files/10288013/2022-12-22T15_15_16_526Z-debug-0.log)

**Comment by JezerM** [comment]
@Cy1der, nodejs v19 is not supported by node-gtk yet, as stated in their README:

> Supported Node.js versions: 14, 16, 17, 18 (other versions should work but are untested)

So, I'd recommend you to use an older version of nodejs.

**Comment by Cy1der** [comment]
How to switch to older version?

**Comment by JezerM** [comment]
Well, it depends on your package management system. If using ArchLinux, install the `nodejs-lts-hydrogen` package.
