### ISSUE TITLE
AUR package request 

### ISSUE THREAD

**Issue by stevenxxiu** [JezerM/nody-greeter#35]
## Environment
- OS: Arch Linux

## Description of feature
Hi, I found your project and it seems to be a good alternative to the dead `lightdm-webkit2-greeter`. Any chance of making an *AUR* package.

**Comment by stevenxxiu** [comment]
Btw I see this depends on `libx11-dev` on the home page, hence *X11*. Does it support *Wayland* instead?

**Comment by JezerM** [comment]
> Any chance of making an AUR package.

Yeah, it's possible, but I haven't had time to do it; perhaps in a future~

> Btw I see this depends on libx11-dev on the home page, hence X11. Does it support Wayland instead? That's a key feature of LightDM.

No, Wayland is not supported in LightDM, hence it's not supported in web-greeter/nody-greeter/sea-greeter.

**Comment by stevenxxiu** [comment]
> No, Wayland is not supported in LightDM, hence it's not supported in web-greeter/nody-greeter/sea-greeter.

It does say on https://github.com/canonical/lightdm:

> Supports different display technologies (X, Mir, Wayland ...).

**Comment by JezerM** [comment]
I guess it means that LightDM can execute those display technologies as sessions. LightDM always executes an X server.

**Comment by stevenxxiu** [comment]
Thanks for the reply. I'm just thinking of getting rid of *X11* entirely in the future so want to get this right.

Looking at `lightdm` dependencies, it includes `xorg-server` anyway so I suppose this doesn't matter much, at least the way things are packaged now.

I googled more and https://lists.freedesktop.org/archives/lightdm/2019-June/001172.html does have the *LightDM* author saying:

> LightDM doesn't depend on X and you can have a Wayland based greeter.
> 
> If you install the greeter .desktop file into /usr/share/lightdm/greeters and set X-LightDM-Session-Type=wayland LightDM will launch this greeter without an X server.

**Comment by JezerM** [comment]
> If you install the greeter .desktop file into /usr/share/lightdm/greeters and set X-LightDM-Session-Type=wayland LightDM will launch this greeter without an X server.

Oh, I didn't know that. So it seems it doesn't have to always use X11, however there are some minor breakpoints about this, like the *layout manager*. LightDM uses libxklavier to manage the current system keyboard layout, which only works on X11; maybe it works on Wayland through X-Wayland, but I'm not sure.

Though, I tried to run web-greeter and nody-greeter in a Wayland environment a long time ago and they did work, so although it's not supported at all, it could be executed in Wayland.

**Comment by stevenxxiu** [comment]
Lately an recent upgrade to `webkit2gtk` has broke `lightdm-webkit-theme-aether` yet again, so I'm looking at this project once more.

I see that someone made a package <https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nody-greeter>. I tried but this does not build, as I'm guessing this project relies on a *Node.js* version that is too old. The latest on *Arch Linux* is v20.6.1, while the readme of this project says it supports up to v16.

I also see some code in this project relies on *X11*. Most projects have moved onto, or are moving onto, pure *Wayland*.

So if you could update the packages for the latest *Node.js*, and give an option for pure *Wayland*, that'll be fantastic!

**Comment by D3vil0p3r** [comment]
@stevenxxiu I installed nody-greeter on my Arch by using **paru** and it has been installed with no issues. Do you know a list of interesting LightDM themes compliant with nody-greeter?

**Comment by stevenxxiu** [comment]
I tried the latest and it still doesn't build with the latest *Node.js* on *Arch Linux*, v22.4.1.

**Comment by JezerM** [comment]
> I tried again and it still doesn't build with the latest *Node.js* on *Arch Linux*, v22.4.1.

The recommended node version is v18, please use it.
