### ISSUE TITLE
can't change keyboard layout

### ISSUE THREAD

**Issue by wa1mi** [JezerM/nody-greeter#38]
## Environment
- OS: Ubuntu 22.10
- nody-greeter version: 1.5.2

## Bug description
error when trying to change keyboard layout

## Screenshots
![Screenshot from 2023-02-24 13-01-14](https://user-images.githubusercontent.com/118893640/221105726-0a4ed8ec-ab7d-403e-8d16-fda0f130c293.png)

**Comment by JezerM** [comment]
Hi! This should be fixed in the latest release~
