### ISSUE TITLE
nody-greeter install issues 

### ISSUE THREAD

**Issue by KittenPixel-cell** [JezerM/nody-greeter#39]
## Environment
- OS: Ubuntu 18.04/Latest Mini ISO
- nody-greeter version: output of `nody-greeter --version`

## Bug description
When I do npm install it is a very big bug jumble

like npm ERR!

## Steps to reproduce
No idea
## Screenshots
![image](https://user-images.githubusercontent.com/79544605/232346083-9d7159dd-36a0-4098-a326-4a49604c2e8c.png)

**Comment by JezerM** [comment]
I see you are using an old version of Node.js. The minimum required version is v12. It seems Ubuntu 18 doesn't provide this version, so you would need to download it from https://nodejs.org/ or update to a newer Ubuntu release.

**Comment by KittenPixel-cell** [comment]
Oh Ok I will close this if it continues after I update ubuntu I will open it back up

**Comment by KittenPixel-cell** [comment]
On rebuild it is now giving a different error
![image](https://user-images.githubusercontent.com/79544605/232355320-8c117414-532f-424c-b4c1-ff4c27e30f91.png)

**Comment by KittenPixel-cell** [comment]
I do have gyp btw

**Comment by KittenPixel-cell** [comment]
Nevermind didn't have all dependencies

**Comment by JezerM** [comment]
Nais

**Comment by KittenPixel-cell** [comment]
npx tsc is erroring now I will send screenshot tomorrow gotta go to sleep and then go to school

**Comment by KittenPixel-cell** [comment]
![image](https://user-images.githubusercontent.com/79544605/232601853-67303363-80d1-4b5a-9979-212e6db2b39f.png)
