### ISSUE TITLE
Error: absolute srcpath does not exist

### ISSUE THREAD

**Issue by steven2024** [JezerM/nody-greeter#44]
## Environment
- OS: [Nobara-37-KDE]
- nody-greeter version: output of `nody-greeter --version` 
(cant use the command since it cant launch)

## Bug description
When running sudo node make install it throws the error Error: absolute srcpath does not exist

## Steps to reproduce
I've installed npm6.14.18 and node v16.20.0 on nobara-37. I have tried going through the commands after installing npm and node. I have downgraded npm and node to a supported version i.e v16 and v6. Using v8 of npm gives the same error and v7 just has an issue with building. 

## Expected behavior
I expected it to be able to just let me install it after building it but I've gone through multiple other errors when building and got them sorted out.

## Screenshots

![image](https://github.com/JezerM/nody-greeter/assets/89735533/c7d7154b-1b85-40ef-9b21-bc0aba039f54)

## Konsole Output
```
[root@penguin-legion nody-greeter]# sudo node make install
Copying nody-greeter to "/"...
/home/penguin/nody-greeter/node_modules/fs-extra/lib/ensure/symlink-paths.js:71
    if (!exists) throw new Error('absolute srcpath does not exist')
                       ^

Error: absolute srcpath does not exist
    at symlinkPathsSync (/home/penguin/nody-greeter/node_modules/fs-extra/lib/ensure/symlink-paths.js:71:24)
    at Object.createSymlinkSync (/home/penguin/nody-greeter/node_modules/fs-extra/lib/ensure/symlink.js:50:20)
    at install (/home/penguin/nody-greeter/install.js:43:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async do_install (/home/penguin/nody-greeter/make.js:69:3)

```

**Comment by JezerM** [comment]
Hi!, this should be fixed on the latest release. If you encounter this issue again, reopen the issue with more information~
