### ISSUE TITLE
Installation Instruction Improvement - TypeScript Compile

### ISSUE THREAD

**Issue by mshernandez5** [JezerM/nody-greeter#5]
Hello!

I was building this project earlier and realized that the TypeScript compiler is never automatically run during the process, which obviously causes issues during the `node make build` step. This is not a huge issue by any means but can save a few people from a little confusion.

It appears that tsc is invoked with the `npm run build` target but this was changed in favor of `node make build` with ed648f4 (which runs the build script indirectly but no longer with the tsc step defined in package.json). Adding a `npx tsc` step to the installation or otherwise making it so this gets run could be helpful.

**Comment by JezerM** [comment]
Oh, sure, I forgot about **tsc**. I'll fix that.

**Comment by JezerM** [comment]
`npx tsc` step added to README :D
