### ISSUE TITLE
:has() support in css

### ISSUE THREAD

**Issue by jw2122** [JezerM/nody-greeter#52]
## Environment
- OS: Manjaro
- nody-greeter version: 1.5.2
## Description of feature

Hi,
first of all I really love your application, thanks for your work.
I tried to create my own theme, but it did not work so i found out that the reason is that i used the :has() operator in my css code. Of course i will use some TypeScript to make it work, but anyway it would be nice to have the :has() operator. 

Thank You for your time,
just wanted to tell you about the feature

**Comment by JezerM** [comment]
Hi, this should be already implemented in the latest release of nody-greeter, which uses Chrome 118.
