### ISSUE TITLE
problem with liblightdm-gobject-dev

### ISSUE THREAD

**Issue by lgor360** [JezerM/nody-greeter#57]
liblightdm-gobject-dev is not available yet... is it possible to do without it?

**Comment by JezerM** [comment]
What do you mean by "liblightdm-gobject-dev" is not available? Which bistro are you using? If there's no dev version, try just with "liblightdm-gobject".

**Comment by lgor360** [comment]
> What do you mean by "liblightdm-gobject-dev" is not available? Which bistro are you using? If there's no dev version, try just with "liblightdm-gobject".

distro: Ubuntu 24.04
sudo apt install liblightdm-gobject-dev 
E: Unable to locate package liblightdm-gobject-dev 
same with liblightdm-gobject

**Comment by JezerM** [comment]
Try with `liblightdm-gobject-1-dev`

**Comment by lgor360** [comment]
> Try with `liblightdm-gobject-1-dev`

thanks!
