### ISSUE TITLE
Rebuild process dosen't succeed

### ISSUE THREAD

**Issue by FarDust** [JezerM/nody-greeter#6]
## Environment
- OS: Pop OS 21.04
- nody-greeter version: 1.2.1

## Bug description
Running install instructions in `npm run rebuild` phase fails

## Steps to reproduce
- Clone repository at 5cbd3acb8265da1ef097c4866cc01d4fa0d0ddcd
- Install dependencies and using node v17.0.1
- run `npm install`
- run `npm run rebuild`

## Expected behavior
Rebuild step completes successfully to continue installation process. 

## Screenshots
![image](https://user-images.githubusercontent.com/26115793/142781095-ec956c5c-8adf-4ef3-824e-71cdb434e29e.png)

**Comment by JezerM** [comment]
Currently, [node-gtk](https://github.com/romgrk/node-gtk/) does not support Node.js v17.

> Supported Node.js versions: 12, 14, 15, 16 (other versions should work but are untested)

So, I recommend to downgrade to some of the Node.js supported versions and try again.

**Comment by FarDust** [comment]
maybe put some badge in the README, like `nodejs lts` for troubleshooting purpose.
i will try again with the new version in a while.

**Comment by FarDust** [comment]
It works fine in PopOS 21.04 with node v16.13.0 (npm v8.1.0)

**Comment by wiggleforlife** [comment]
Doesn't work for me, results in the same issue. I've tried v15.14.0, v16.13.0, v16.13.1, and v16.4.2. None work. I'm on Arch with kernel 5.15-7.

**Comment by JezerM** [comment]
@wiggleforlife Is your log the same? If not, could you provide it?

**Comment by wiggleforlife** [comment]
My apologies, it's gone and worked now that it's the next day. This time, I have `web-greeter` installed. I didn't see that in the README, but is it required?

**Comment by JezerM** [comment]
Glad it worked! But nope, web-greeter and nody-greeter are independent projects, no one requires the other.

**Comment by BobbyBabes** [comment]
With `nvm` you can run any version of nodejs in parallel : [https://github.com/nvm-sh/nvm](https://github.com/nvm-sh/nvm).

**Comment by BodeSpezial** [comment]
I had the same issue and as far as I can tell `gobject-introspection` is not a dependency of lightdm (anymore?) (or anything else which is installed).
But it is a dependency of web-greeter, thus fixing the issue when installing web-greeter.
