### ISSUE TITLE
Error while starting - nody-greeter --debug

### ISSUE THREAD

**Issue by gitneeraj** [JezerM/nody-greeter#9]
## Environment
- OS: Arch linux DE: XFCE
- nody-greeter version: output of `nody-greeter --version` 1.3.0

## Bug description
All the build steps work fine but running `nody-greeter --debug` throws below error
## Steps to reproduce
`nody-greeter --debug` throws erros

## Expected behavior
Should open the greeter with specified theme

## Screenshots
![nody-greeter-issue](https://user-images.githubusercontent.com/36226187/147819604-861122a8-db22-49e6-a366-290725f42343.png)

**Comment by JezerM** [comment]
According to the error message, `libffi.so.8` couldn't be found, so maybe `libffi` is not installed/upgraded. Or perhaps, **pkg-config** can't find it inside the `PKG_CONFIG_PATH` variable, or `pkg-config` is not installed.

So, you could try to install `libffi` (if not installed). Then, check if it does exists with `pkg-config --exists libffi`; if it doesn't, try to find `libffi.so.8` in all your system, though it should be inside `/usr/lib/` (or its subdirectories), and add the directory where you found it to the `PKG_CONFIG_PATH` variable (though it should be globally).

**Comment by gitneeraj** [comment]
Well, installed this on my main Arch machine instead of in VirtualBox and it worked! There were some hiccups but I managed to troubleshoot them(one was on the step `npm run rebuild`).
I am the maintainer of the theme called `Reactive` https://github.com/gitneeraj/lightdm-webkit2-theme-reactive and it works with nody-greeter(at least at a glance) without any issues so far. I have only one question, how do I `Inspect Element` when on debug mode is set to `True`? (`nody-greeter --debug).

Thanks for making nody-greeter. I always wanted chromium instead of webkit and I LOVE node.js

**Comment by JezerM** [comment]
Glad it worked!

To open dev tools, you can press `Ctrl+Shift+I`, or right click to open context menu and click on `inspect element`.

**Comment by gitneeraj** [comment]
That's the thing, its not working for me inside the debug window when I start with 'nody-greeter --debug' neither with 'Ctrl+Shift+I'

**Comment by JezerM** [comment]
Oh, I noticed the context menu is not opening... However, if `Ctrl+Shift+I` does not work, you should be able to open dev tools with the menu bar at top: View -> Toggle Developer Tools

![Screenshot_2022-01-02-38_1366x768](https://user-images.githubusercontent.com/59768785/147882819-d0b47a02-ef21-417a-b222-f2f5bae5eea9.png)

**Comment by gitneeraj** [comment]
Alright, somehow I missed noticing that menu bar. Thanks that works!
Another question that I am curious about to know and then you can mark this issue closed - 
I see you use `web-greeter://` protocol which is nice but why it starts at `/app/<theme-location` and why not just the `<theme-location` (that is from `/usr/..`)?
![nody-greeter-q](https://user-images.githubusercontent.com/36226187/147884230-1d6420c8-5279-48b1-bf10-62883b618572.png)

**Comment by JezerM** [comment]
The `app` section is for correction purposes, as it acts like host and hostname. Without it, the first "element" in the path would be used for the host/hostname, and so the path would be `web-greeter://usr/usr/share/web-greeter/themes/reactive/.index.html`; this looks weird and sometimes can create issues when handling with other paths, like `web-greeter://usr/etc/something` or `web-greeter://usr/tmp/something`. Even if this path is replaced with `web-greeter://usr/share/path/to/theme`, `usr/` is still the hostname, so it would check for `/share/path/to/theme` instead of `/usr/share/path/to/theme` and won't show the theme.
